[package]
name = "icer"
version = "0.1.0"
authors = ["Kleidi Bujari"]
edition = "2021"
repository = "https://github.com/kbujari/icer"
license = "MIT"

[dependencies]
image = { version = "0.24.6", optional = true }

[features]
render = ["dep:image"]
default = ["render"]
